### ISSUE TITLE
Evitar usar sobreingenieria

### ISSUE THREAD

**Issue by whitehatdevv** [OvidioSantoro/react-simple-counter#3]
https://github.com/OvidioSantoro/react-simple-counter/blob/be157acc8bf24029969e06ca33fde019a97bf929/src/js/component/home.jsx#L1

El componente `<Home>` aquí no es neceario, es montar una capa más para nada exactamente, elimina ese componente y adapta de nuevo tu código para que funcione perfectamente sin ese componente. 

PD: Cuando hayas terminado cierra el ISSUE y sube de nuevo el ejercicio en BreathCode.

**Comment by OvidioSantoro** [comment]
- Componente `<Home>` eliminado. Ahora la aplicación llama directamente al componente principal, `<SecondsCounter>` sin una capa intermedia.
- Cambiado el `<title>` del HTML, que continuaba siendo el predefinido por el boilerplate.

**Comment by whitehatdevv** [comment]
Recibido
